Rework attribute generator and use now registry entries
OneLiteFeatherNET/Microtus pull request #107
Opened 2024-02-16 10:34 UTC by TheMeinerLP

## Proposed changes

This PR serves the purpose of better generating the attributes. It uses the standard registry system from Minestom to avoid errors and increase consistency in the code. I have discarded the original design and added two new classes. One for the entry from the file for the registry and one for the interface implementation to add the data as getter etc. The attribute class became an interface to follow the structure. The enum generation I created before was replaced with an interface and the enum generator was deleted as a class.

In the end you can now call the class via static attributes as before but update it faster in the future.

## Types of changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [X] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of
them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before
merging your code._

- [X] I have read the CONTRIBUTING.md
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you
did and what alternatives you considered, etc...

2024-02-16 12:28 UTC, theEvilReaper commented on minestom-patches/0015-Add-attribute-generator.patch
> -+import com.squareup.javapoet.*;
Don't use wildcard imports there

2024-02-16 12:28 UTC, theEvilReaper commented on minestom-patches/0015-Add-attribute-generator.patch
> ++
We should annotate this with the `ApiStatus.NonExtendable` annotation to indicate that the class can't be extended

2024-02-16 12:28 UTC, theEvilReaper commented on minestom-patches/0015-Add-attribute-generator.patch
> ++    public AttributeImpl(Registry.AttributeEntry entry) {
Add `NotNull` annotation

2024-02-16 12:28 UTC, theEvilReaper commented on minestom-patches/0015-Add-attribute-generator.patch
>  +    public synchronized void register(Attribute attribute) {
Add `NotNull` annotation

2024-02-16 12:28 UTC, theEvilReaper commented on minestom-patches/0015-Add-attribute-generator.patch
>  +public final class AttributeManager {
Also here annotate the class with `ApiStatus.NonExtendable`

2024-02-16 12:28 UTC, theEvilReaper commented on minestom-patches/0015-Add-attribute-generator.patch
> ++        public AttributeEntry(String namespace, Properties main, Properties custom) {
Annotate the parameters with `NotNull` or `Nullable` depends on the case

2024-02-21 10:41 UTC, theEvilReaper requested changes

2024-02-21 10:41 UTC, theEvilReaper commented on minestom-patches/0015-Add-attribute-generator.patch
> ++    @NotNull
We can move the `NotNull` annotation before the NameSpaceID definition. So the line looks like this `NotNull NameSpaceID namespace();` (Dont forget to add the annotation char. I don't want to tag someone here)

2024-02-21 10:41 UTC, theEvilReaper commented on minestom-patches/0015-Add-attribute-generator.patch
> ++    float minValue();
Add between each getter an empty line to increate readability. Also some annotation would be nice

2024-02-21 10:43 UTC, TheMeinerLP commented on minestom-patches/0015-Add-attribute-generator.patch
> ++    float minValue();
Thats not longer valid because outdated view from you.
<img width="815" alt="image" src="https://github.com/OneLiteFeatherNET/Microtus/assets/6745190/ac1aef82-0248-4974-a708-778f339c4093">

2024-02-27 20:08 UTC, merged