[#34] Better Notification System
OneLiteFeatherNET/Microtus pull request #35
Opened 2024-05-26 18:21 UTC by TheMeinerLP

## Proposed changes

Fixes #34

This PR aims to create a new interface to send better notifications. Old code was removed from the demo and an obsolescence message was added to the old notification system. 
The new design is based on a Creation Pattern or Buidler Pattern

## Types of changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of
them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before
merging your code._

- [X] I have read the CONTRIBUTING.md
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you
did and what alternatives you considered, etc...

2024-05-26 20:02 UTC, theEvilReaper requested changes

2024-05-26 20:02 UTC, theEvilReaper commented on src/main/java/net/minestom/server/notifications/Notification.java
> +
Unnecessary empty lines

2024-05-26 20:02 UTC, theEvilReaper commented on src/main/java/net/minestom/server/notifications/NotificationBuilder.java
> +
Unnecessary empty line

2024-05-26 20:02 UTC, theEvilReaper commented on src/main/java/net/minestom/server/notifications/Notification.java
> +
Unnecessary empty line

2024-05-26 20:02 UTC, theEvilReaper commented on src/main/java/net/minestom/server/notifications/Notification.java
> +
Unnecessary empty line

2024-05-27 12:43 UTC, Codestech1 approved these changes

2024-05-27 15:39 UTC, theEvilReaper approved these changes

2024-05-27 15:41 UTC, merged